- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120 hrs
    TRAINER: shivakumar
  tasks: 
    - name: print the variables
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINSE }}"  