- name: vars files
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter the course name
      private: false
    - name: DURATION
      prompt: please enter the duration
      private: false
    - name: TRAINER
      prompt: please enter the trainer name    
  tasks:
    - name: print the vars
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, duration is {{ DURATION}}, trainer is {{ TRAINER }}"  