- name: devops info
  hosts: local
  connection: local
  vars:
    course_name: "devops with aws"
    duration: 120hrs
    topics:
      - linux
      - aws
      - devops
      - shell
    live: true
    tools:
      ci: jenkins
      cloud: aws
      contanerization: docker
    tasks:
      - name: print the info
        ansible.builtin.debug:
          msg: "hello i am learning {{ course_name }}, duration is {{ duration }}, topics in it are: {{ topics }}, is it live: {{ live }}, tools are used {{ tools }}"    