- name: check value is greater than 10 or not
  hosts: local
  connection: local
  vars: 
    my_number: 14
  tasks:
    - name: print the info
      ansible.builtin.debug:
       msg: "given number is {{ my_number }} greater than 10"
      when: my_number > 10
