- name: loops
  hosts: local
  connection: local
  tasks:
    - name: loops
      ansible.builtin.debug:
        msg: "hello {{ item }}"
      loop:
        - ramesh
        - suresh
        - shrihan  