- name: install packages
  hosts: web
  become: yes
  tasks:
   - name: install packages
     ansible.builtin.package:
       name: "{{ item }}"
       state: present
     loop:
      - gcc
      - mysql
      - git  