- name: install packages
  hosts: web
  become: yes
  tasks:
   - name: install packages
     ansible.builtin.package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
     loop:
      - { name: 'zip' , state: 'present'}
      - { name: 'git' , state: 'present'}
      - { name: 'mysql' , state: 'present'}  
      - { name: 'gcc' , state: 'present'}