- name: filters
  hosts: local
  connection: local
  tasks:
    - name: handle the undefine variables
      ansible.builtin.debug:
        msg: "hello {{ person | default('shrihan') }}"

    - name: convert string to list
      vars:
        fruits: "apple, banana, orange"
      ansible.builtin.debug:
        msg: " fryuits areL: {{ fruits | split (',') }}"    

    - name: convert map into list
      vars:
        course:
          name: ansible
          duaration: 2hrs
          trainder: shiva
      ansible.builtin.debug:
        msg: "course info: {{ course | dict2items}}"        